---
# handlers file for ansible-linuxdash

# fpm
- name: service restart php-fpm
  tags: linuxdash
  service:
    state=restarted
    name={{ linuxdash_fpm_service }}

# nginx
- name: service restart nginx
  tags: linuxdash
  service:
    state=restarted
    name=nginx

